# en_sen_train.yaml

## Where the samples will be written
save_data: en-sen/run/example
# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
    corpus_1:
        path_src: data/src-train.txt
        path_tgt: data/tgt-train.txt
    valid:
        path_src: data/src-val.txt
        path_tgt: data/tgt-val.txt

# Vocabulary files that were just created
src_vocab: en-sen/run/example.vocab.src
tgt_vocab: en-sen/run/example.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

#parameters
global_attention: general
# If training from a checkpoint then this is the path to the pretrained model’s state_dict.
# train_from = /PATH
encoder_type: brnn
layers: 2
feat_vec_exponent: 0.7
seed: 3435
rnn_type: LSTM
max_grad_norm: 5
param_init: 0.1
optim: sgd
sample: 0
learning_rate_decay: 0.7
learning_rate: 1.0
report_every: 50

# Where to save the checkpoints
save_model: en-sen/run/model
save_checkpoint_steps: 500
train_steps: 60000
valid_steps: 5000